name: Cherry Push

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cherry:
    name: Push metrics and contributions
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: test
        run: |
          bundle exec rubocop
